### ISSUE TITLE
Exception happened during processing of request from: BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by abrilevskiy** [mbugert/connectbox-prometheus#10]
Exception happened during processing of request from
Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/lib/python3.7/http/server.py", line 414, in handle_one_request
    method()
  File "/usr/local/lib/python3.7/dist-packages/prometheus_client/exposition.py", line 175, in do_GET
    self.wfile.write(output)
  File "/usr/lib/python3.7/socketserver.py", line 799, in write
    self._sock.sendall(b)
BrokenPipeError: [Errno 32] Broken pipe

**Comment by mbugert** [comment]
Hi, thanks for reporting.
Could you please provide more details on the steps which led to this error message? What was supposed to happen? Also, which version of the exporter are you using?

**Comment by mbugert** [comment]
Closing due to inactivity.
